name: Rust

on:
  push:
    branches: [ cmaf ]
  pull_request:
    branches: [ cmaf ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup rust smart caching
        uses: Swatinem/rust-cache@v2

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --no-deps -- -D warnings

      - name: Cargo build
        run: cargo build --all-targets

      - name: Cargo test
        run: cargo test

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Build library on MSRV
        run: cargo build --lib
